
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.slothcraft.init;

import net.slothcraft.item.ZincSwordItem;
import net.slothcraft.item.ZincShovelItem;
import net.slothcraft.item.ZincPlateItemItem;
import net.slothcraft.item.ZincPickaxeItem;
import net.slothcraft.item.ZincIngotItem;
import net.slothcraft.item.ZincHoeItem;
import net.slothcraft.item.ZincGearItemItem;
import net.slothcraft.item.ZincAxeItem;
import net.slothcraft.item.ZincArmorItem;
import net.slothcraft.item.WoodenGearItemItem;
import net.slothcraft.item.WoodPlateItemItem;
import net.slothcraft.item.WitherStaffRangedWeaponItem;
import net.slothcraft.item.WhiskItemItem;
import net.slothcraft.item.VioletHazeSeedItemItem;
import net.slothcraft.item.VioletHazeNugItemItem;
import net.slothcraft.item.VioletHazeLeafItemItem;
import net.slothcraft.item.VioletHazeKiefItemItem;
import net.slothcraft.item.VioletHazeGrinderItemItem;
import net.slothcraft.item.UraniumSwordItem;
import net.slothcraft.item.UraniumShovelItem;
import net.slothcraft.item.UraniumPlateItemItem;
import net.slothcraft.item.UraniumPickaxeItem;
import net.slothcraft.item.UraniumIngotItem;
import net.slothcraft.item.UraniumHoeItem;
import net.slothcraft.item.UraniumGearItemItem;
import net.slothcraft.item.UraniumAxeItem;
import net.slothcraft.item.UraniumArmorItem;
import net.slothcraft.item.TitaniumSwordItem;
import net.slothcraft.item.TitaniumShovelItem;
import net.slothcraft.item.TitaniumPlateItemItem;
import net.slothcraft.item.TitaniumPickaxeItem;
import net.slothcraft.item.TitaniumIngotItem;
import net.slothcraft.item.TitaniumHoeItem;
import net.slothcraft.item.TitaniumGearItemItem;
import net.slothcraft.item.TitaniumAxeItem;
import net.slothcraft.item.TitaniumArmorItem;
import net.slothcraft.item.TinSwordItem;
import net.slothcraft.item.TinShovelItem;
import net.slothcraft.item.TinPlateItemItem;
import net.slothcraft.item.TinPickaxeItem;
import net.slothcraft.item.TinIngotItem;
import net.slothcraft.item.TinHoeItem;
import net.slothcraft.item.TinGearItemItem;
import net.slothcraft.item.TinAxeItem;
import net.slothcraft.item.TinArmorItem;
import net.slothcraft.item.StonePlateItemItem;
import net.slothcraft.item.StoneGearItemItem;
import net.slothcraft.item.SteelSwordItem;
import net.slothcraft.item.SteelShovelItem;
import net.slothcraft.item.SteelPlateItemItem;
import net.slothcraft.item.SteelPickaxeItem;
import net.slothcraft.item.SteelIngotItem;
import net.slothcraft.item.SteelHoeItem;
import net.slothcraft.item.SteelGearItemItem;
import net.slothcraft.item.SteelAxeItem;
import net.slothcraft.item.SteelArmorItem;
import net.slothcraft.item.StaffStickItemItem;
import net.slothcraft.item.SilverSwordItem;
import net.slothcraft.item.SilverShovelItem;
import net.slothcraft.item.SilverPlateItemItem;
import net.slothcraft.item.SilverPickaxeItem;
import net.slothcraft.item.SilverIngotItem;
import net.slothcraft.item.SilverHoeItem;
import net.slothcraft.item.SilverGearItemItem;
import net.slothcraft.item.SilverAxeItem;
import net.slothcraft.item.SilverArmorItem;
import net.slothcraft.item.ShinyDiamondItem;
import net.slothcraft.item.SaltFoodItem;
import net.slothcraft.item.RubySwordItem;
import net.slothcraft.item.RubyShovelItem;
import net.slothcraft.item.RubyPlateItemItem;
import net.slothcraft.item.RubyPickaxeItem;
import net.slothcraft.item.RubyHoeItem;
import net.slothcraft.item.RubyGemItem;
import net.slothcraft.item.RubyGearItemItem;
import net.slothcraft.item.RubyAxeItem;
import net.slothcraft.item.RubyArmorItem;
import net.slothcraft.item.RedstonePlateItemItem;
import net.slothcraft.item.RedstoneGearItemItem;
import net.slothcraft.item.QuartzPlateItemItem;
import net.slothcraft.item.QuartzGearItemItem;
import net.slothcraft.item.PoisonStaffRangedWeaponItem;
import net.slothcraft.item.PlatinumSwordItem;
import net.slothcraft.item.PlatinumShovelItem;
import net.slothcraft.item.PlatinumPlateItemItem;
import net.slothcraft.item.PlatinumPickaxeItem;
import net.slothcraft.item.PlatinumIngotItem;
import net.slothcraft.item.PlatinumHoeItem;
import net.slothcraft.item.PlatinumGearItemItem;
import net.slothcraft.item.PlatinumAxeItem;
import net.slothcraft.item.PlatinumArmorItem;
import net.slothcraft.item.PlateHammerItemItem;
import net.slothcraft.item.PieFoodItem;
import net.slothcraft.item.PackedGlassReceptacleFoodItem;
import net.slothcraft.item.OsmiumSwordItem;
import net.slothcraft.item.OsmiumShovelItem;
import net.slothcraft.item.OsmiumPlateItemItem;
import net.slothcraft.item.OsmiumPickaxeItem;
import net.slothcraft.item.OsmiumIngotItem;
import net.slothcraft.item.OsmiumHoeItem;
import net.slothcraft.item.OsmiumGearItemItem;
import net.slothcraft.item.OsmiumAxeItem;
import net.slothcraft.item.OsmiumArmorItem;
import net.slothcraft.item.OrangeFoodItem;
import net.slothcraft.item.ObsidianPlateItemItem;
import net.slothcraft.item.ObsidianGearItemItem;
import net.slothcraft.item.NickelSwordItem;
import net.slothcraft.item.NickelShovelItem;
import net.slothcraft.item.NickelPlateItemItem;
import net.slothcraft.item.NickelPickaxeItem;
import net.slothcraft.item.NickelIngotItem;
import net.slothcraft.item.NickelHoeItem;
import net.slothcraft.item.NickelGearItemItem;
import net.slothcraft.item.NickelAxeItem;
import net.slothcraft.item.NickelArmorItem;
import net.slothcraft.item.MithrilSwordItem;
import net.slothcraft.item.MithrilShovelItem;
import net.slothcraft.item.MithrilPlateItemItem;
import net.slothcraft.item.MithrilPickaxeItem;
import net.slothcraft.item.MithrilIngotItem;
import net.slothcraft.item.MithrilHoeItem;
import net.slothcraft.item.MithrilGearItemItem;
import net.slothcraft.item.MithrilAxeItem;
import net.slothcraft.item.MithrilArmorItem;
import net.slothcraft.item.MinceFoodItem;
import net.slothcraft.item.LeadSwordItem;
import net.slothcraft.item.LeadShovelItem;
import net.slothcraft.item.LeadPlateItemItem;
import net.slothcraft.item.LeadPickaxeItem;
import net.slothcraft.item.LeadIngotItem;
import net.slothcraft.item.LeadHoeItem;
import net.slothcraft.item.LeadGearItemItem;
import net.slothcraft.item.LeadAxeItem;
import net.slothcraft.item.LeadArmorItem;
import net.slothcraft.item.LapisPlateItemItem;
import net.slothcraft.item.LapisGearItemItem;
import net.slothcraft.item.KnifeItemItem;
import net.slothcraft.item.JadeSwordItem;
import net.slothcraft.item.JadeShovelItem;
import net.slothcraft.item.JadePlateItemItem;
import net.slothcraft.item.JadePickaxeItem;
import net.slothcraft.item.JadeHoeItem;
import net.slothcraft.item.JadeGemItem;
import net.slothcraft.item.JadeGearItemItem;
import net.slothcraft.item.JadeAxeItem;
import net.slothcraft.item.JadeArmorItem;
import net.slothcraft.item.IronPlateItemItem;
import net.slothcraft.item.IronGearItemItem;
import net.slothcraft.item.IridiumSwordItem;
import net.slothcraft.item.IridiumShovelItem;
import net.slothcraft.item.IridiumPlateItemItem;
import net.slothcraft.item.IridiumPickaxeItem;
import net.slothcraft.item.IridiumIngotItem;
import net.slothcraft.item.IridiumHoeItem;
import net.slothcraft.item.IridiumGearItemItem;
import net.slothcraft.item.IridiumAxeItem;
import net.slothcraft.item.IridiumArmorItem;
import net.slothcraft.item.IceStaffRangedWeaponItem;
import net.slothcraft.item.GoldPlateItemItem;
import net.slothcraft.item.GoldGearItemItem;
import net.slothcraft.item.GobberPlateItemItem;
import net.slothcraft.item.GobberNetherPlateItemItem;
import net.slothcraft.item.GobberNetherGearItemItem;
import net.slothcraft.item.GobberGearItemItem;
import net.slothcraft.item.GobberEndPlateItemItem;
import net.slothcraft.item.GobberEndGearItemItem;
import net.slothcraft.item.GlassReceptacleItemItem;
import net.slothcraft.item.GearMoldItemItem;
import net.slothcraft.item.FlourFoodItem;
import net.slothcraft.item.FlintPlateItemItem;
import net.slothcraft.item.FlintGearItemItem;
import net.slothcraft.item.FireStaffRangedWeaponItem;
import net.slothcraft.item.EmeraldPlateItemItem;
import net.slothcraft.item.EmeraldGearItemItem;
import net.slothcraft.item.DoughFoodItem;
import net.slothcraft.item.DiamondPlateItemItem;
import net.slothcraft.item.DiamondGearItemItem;
import net.slothcraft.item.CreamFoodItem;
import net.slothcraft.item.CopperSwordItem;
import net.slothcraft.item.CopperShovelItem;
import net.slothcraft.item.CopperPlateItemItem;
import net.slothcraft.item.CopperPickaxeItem;
import net.slothcraft.item.CopperHoeItem;
import net.slothcraft.item.CopperGearItemItem;
import net.slothcraft.item.CopperAxeItem;
import net.slothcraft.item.CopperArmorItem;
import net.slothcraft.item.ChromiumSwordItem;
import net.slothcraft.item.ChromiumShovelItem;
import net.slothcraft.item.ChromiumPlateItemItem;
import net.slothcraft.item.ChromiumPickaxeItem;
import net.slothcraft.item.ChromiumIngotItem;
import net.slothcraft.item.ChromiumHoeItem;
import net.slothcraft.item.ChromiumGearItemItem;
import net.slothcraft.item.ChromiumAxeItem;
import net.slothcraft.item.ChromiumArmorItem;
import net.slothcraft.item.CheeseFoodItem;
import net.slothcraft.item.ButterFoodItem;
import net.slothcraft.item.BananaFoodItem;
import net.slothcraft.item.BaconFoodItem;
import net.slothcraft.item.AmethystSwordItem;
import net.slothcraft.item.AmethystShovelItem;
import net.slothcraft.item.AmethystPlateItemItem;
import net.slothcraft.item.AmethystPickaxeItem;
import net.slothcraft.item.AmethystHoeItem;
import net.slothcraft.item.AmethystGemItem;
import net.slothcraft.item.AmethystGearItemItem;
import net.slothcraft.item.AmethystAxeItem;
import net.slothcraft.item.AmethystArmorItem;
import net.slothcraft.item.AluminumSwordItem;
import net.slothcraft.item.AluminumShovelItem;
import net.slothcraft.item.AluminumPlateItemItem;
import net.slothcraft.item.AluminumPickaxeItem;
import net.slothcraft.item.AluminumIngotItem;
import net.slothcraft.item.AluminumHoeItem;
import net.slothcraft.item.AluminumGearItemItem;
import net.slothcraft.item.AluminumAxeItem;
import net.slothcraft.item.AluminumArmorItem;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.event.RegistryEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import java.util.List;
import java.util.ArrayList;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class SlothcraftModItems {
	private static final List<Item> REGISTRY = new ArrayList<>();
	public static final Item ALUMINUM_GEAR = register(new AluminumGearItemItem());
	public static final Item AMETHYST_GEAR_ITEM = register(new AmethystGearItemItem());
	public static final Item CHROMIUM_GEAR_ITEM = register(new ChromiumGearItemItem());
	public static final Item COPPER_GEAR_ITEM = register(new CopperGearItemItem());
	public static final Item DIAMOND_GEAR_ITEM = register(new DiamondGearItemItem());
	public static final Item EMERALD_GEAR_ITEM = register(new EmeraldGearItemItem());
	public static final Item FLINT_GEAR_ITEM = register(new FlintGearItemItem());
	public static final Item GOBBER_END_GEAR_ITEM = register(new GobberEndGearItemItem());
	public static final Item GOBBER_GEAR_ITEM = register(new GobberGearItemItem());
	public static final Item GOBBER_NETHER_GEAR_ITEM = register(new GobberNetherGearItemItem());
	public static final Item GOLD_GEAR_ITEM = register(new GoldGearItemItem());
	public static final Item IRIDIUM_GEAR_ITEM = register(new IridiumGearItemItem());
	public static final Item IRON_GEAR_ITEM = register(new IronGearItemItem());
	public static final Item JADE_GEAR_ITEM = register(new JadeGearItemItem());
	public static final Item LAPIS_GEAR_ITEM = register(new LapisGearItemItem());
	public static final Item LEAD_GEAR_ITEM = register(new LeadGearItemItem());
	public static final Item MITHRIL_GEAR_ITEM = register(new MithrilGearItemItem());
	public static final Item NICKEL_GEAR_ITEM = register(new NickelGearItemItem());
	public static final Item OBSIDIAN_GEAR_ITEM = register(new ObsidianGearItemItem());
	public static final Item OSMIUM_GEAR_ITEM = register(new OsmiumGearItemItem());
	public static final Item PLATINUM_GEAR_ITEM = register(new PlatinumGearItemItem());
	public static final Item QUARTZ_GEAR_ITEM = register(new QuartzGearItemItem());
	public static final Item REDSTONE_GEAR_ITEM = register(new RedstoneGearItemItem());
	public static final Item RUBY_GEAR_ITEM = register(new RubyGearItemItem());
	public static final Item SILVER_GEAR_ITEM = register(new SilverGearItemItem());
	public static final Item STEEL_GEAR_ITEM = register(new SteelGearItemItem());
	public static final Item STONE_GEAR_ITEM = register(new StoneGearItemItem());
	public static final Item TIN_GEAR_ITEM = register(new TinGearItemItem());
	public static final Item TITANIUM_GEAR_ITEM = register(new TitaniumGearItemItem());
	public static final Item URANIUM_GEAR_ITEM = register(new UraniumGearItemItem());
	public static final Item WOODEN_GEAR_ITEM = register(new WoodenGearItemItem());
	public static final Item ZINC_GEAR_ITEM = register(new ZincGearItemItem());
	public static final Item GEAR_MOLD_ITEM = register(new GearMoldItemItem());
	public static final Item GEARS_MAKER_BLOCK = register(SlothcraftModBlocks.GEARS_MAKER_BLOCK,
			SlothcraftModTabs.TAB_SLOTH_CRAFT_GEARS_CREATIVE_TAB);
	public static final Item ALUMINUM_PLATE_ITEM = register(new AluminumPlateItemItem());
	public static final Item AMETHYST_PLATE_ITEM = register(new AmethystPlateItemItem());
	public static final Item CHROMIUM_PLATE_ITEM = register(new ChromiumPlateItemItem());
	public static final Item COPPER_PLATE_ITEM = register(new CopperPlateItemItem());
	public static final Item DIAMOND_PLATE_ITEM = register(new DiamondPlateItemItem());
	public static final Item EMERALD_PLATE_ITEM = register(new EmeraldPlateItemItem());
	public static final Item FLINT_PLATE_ITEM = register(new FlintPlateItemItem());
	public static final Item GOBBER_END_PLATE_ITEM = register(new GobberEndPlateItemItem());
	public static final Item GOBBER_NETHER_PLATE_ITEM = register(new GobberNetherPlateItemItem());
	public static final Item GOBBER_PLATE_ITEM = register(new GobberPlateItemItem());
	public static final Item GOLD_PLATE_ITEM = register(new GoldPlateItemItem());
	public static final Item IRIDIUM_PLATE_ITEM = register(new IridiumPlateItemItem());
	public static final Item IRON_PLATE_ITEM = register(new IronPlateItemItem());
	public static final Item JADE_PLATE_ITEM = register(new JadePlateItemItem());
	public static final Item LAPIS_PLATE_ITEM = register(new LapisPlateItemItem());
	public static final Item LEAD_PLATE_ITEM = register(new LeadPlateItemItem());
	public static final Item MITHRIL_PLATE_ITEM = register(new MithrilPlateItemItem());
	public static final Item NICKEL_PLATE_ITEM = register(new NickelPlateItemItem());
	public static final Item OBSIDIAN_PLATE_ITEM = register(new ObsidianPlateItemItem());
	public static final Item OSMIUM_PLATE_ITEM = register(new OsmiumPlateItemItem());
	public static final Item PLATINUM_PLATE_ITEM = register(new PlatinumPlateItemItem());
	public static final Item QUARTZ_PLATE_ITEM = register(new QuartzPlateItemItem());
	public static final Item REDSTONE_PLATE_ITEM = register(new RedstonePlateItemItem());
	public static final Item RUBY_PLATE_ITEM = register(new RubyPlateItemItem());
	public static final Item SILVER_PLATE_ITEM = register(new SilverPlateItemItem());
	public static final Item STEEL_PLATE_ITEM = register(new SteelPlateItemItem());
	public static final Item STONE_PLATE_ITEM = register(new StonePlateItemItem());
	public static final Item TIN_PLATE_ITEM = register(new TinPlateItemItem());
	public static final Item TITANIUM_PLATE_ITEM = register(new TitaniumPlateItemItem());
	public static final Item URANIUM_PLATE_ITEM = register(new UraniumPlateItemItem());
	public static final Item WOOD_PLATE_ITEM = register(new WoodPlateItemItem());
	public static final Item ZINC_PLATE_ITEM = register(new ZincPlateItemItem());
	public static final Item PLATE_HAMMER_ITEM = register(new PlateHammerItemItem());
	public static final Item PLATES_MAKER_BLOCK = register(SlothcraftModBlocks.PLATES_MAKER_BLOCK,
			SlothcraftModTabs.TAB_SLOTH_CRAFT_PLATES_CREATIVE_TAB);
	public static final Item BACON_FOOD = register(new BaconFoodItem());
	public static final Item ORANGE_FOOD = register(new OrangeFoodItem());
	public static final Item BANANA_FOOD = register(new BananaFoodItem());
	public static final Item CHEESE_FOOD = register(new CheeseFoodItem());
	public static final Item DOUGH_FOOD = register(new DoughFoodItem());
	public static final Item FLOUR_FOOD = register(new FlourFoodItem());
	public static final Item BUTTER_FOOD = register(new ButterFoodItem());
	public static final Item CREAM_FOOD = register(new CreamFoodItem());
	public static final Item SALT_FOOD = register(new SaltFoodItem());
	public static final Item MINCE_FOOD = register(new MinceFoodItem());
	public static final Item PIE_FOOD = register(new PieFoodItem());
	public static final Item KNIFE_ITEM = register(new KnifeItemItem());
	public static final Item WHISK_ITEM = register(new WhiskItemItem());
	public static final Item SHINY_DIAMOND = register(new ShinyDiamondItem());
	public static final Item VIOLET_HAZE_PLANT = register(SlothcraftModBlocks.VIOLET_HAZE_PLANT, null);
	public static final Item VIOLET_HAZE_SEED_ITEM = register(new VioletHazeSeedItemItem());
	public static final Item VIOLET_HAZE_NUG_ITEM = register(new VioletHazeNugItemItem());
	public static final Item VIOLET_HAZE_KIEF_ITEM = register(new VioletHazeKiefItemItem());
	public static final Item GLASS_RECEPTACLE_ITEM = register(new GlassReceptacleItemItem());
	public static final Item VIOLET_HAZE_LEAF_ITEM = register(new VioletHazeLeafItemItem());
	public static final Item PACKED_GLASS_RECEPTACLE_FOOD = register(new PackedGlassReceptacleFoodItem());
	public static final Item VIOLET_HAZE_GRINDER_ITEM = register(new VioletHazeGrinderItemItem());
	public static final Item STAFF_STICK_ITEM = register(new StaffStickItemItem());
	public static final Item FIRE_STAFF_RANGED_WEAPON = register(new FireStaffRangedWeaponItem());
	public static final Item POISON_STAFF_RANGED_WEAPON = register(new PoisonStaffRangedWeaponItem());
	public static final Item ICE_STAFF_RANGED_WEAPON = register(new IceStaffRangedWeaponItem());
	public static final Item WITHER_STAFF_RANGED_WEAPON = register(new WitherStaffRangedWeaponItem());
	public static final Item ALUMINUM_ORE = register(SlothcraftModBlocks.ALUMINUM_ORE, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item ALUMINUM_ORE_BLOCK = register(SlothcraftModBlocks.ALUMINUM_ORE_BLOCK,
			SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item ALUMINUM_INGOT = register(new AluminumIngotItem());
	public static final Item ALUMINUM_PICKAXE = register(new AluminumPickaxeItem());
	public static final Item ALUMINUM_AXE = register(new AluminumAxeItem());
	public static final Item ALUMINUM_SWORD = register(new AluminumSwordItem());
	public static final Item ALUMINUM_SHOVEL = register(new AluminumShovelItem());
	public static final Item ALUMINUM_HOE = register(new AluminumHoeItem());
	public static final Item ALUMINUM_ARMOR_HELMET = register(new AluminumArmorItem.Helmet());
	public static final Item ALUMINUM_ARMOR_CHESTPLATE = register(new AluminumArmorItem.Chestplate());
	public static final Item ALUMINUM_ARMOR_LEGGINGS = register(new AluminumArmorItem.Leggings());
	public static final Item ALUMINUM_ARMOR_BOOTS = register(new AluminumArmorItem.Boots());
	public static final Item AMETHYST_ORE = register(SlothcraftModBlocks.AMETHYST_ORE, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item AMETHYST_ORE_BLOCK = register(SlothcraftModBlocks.AMETHYST_ORE_BLOCK,
			SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item AMETHYST_GEM = register(new AmethystGemItem());
	public static final Item AMETHYST_PICKAXE = register(new AmethystPickaxeItem());
	public static final Item AMETHYST_AXE = register(new AmethystAxeItem());
	public static final Item AMETHYST_SWORD = register(new AmethystSwordItem());
	public static final Item AMETHYST_SHOVEL = register(new AmethystShovelItem());
	public static final Item AMETHYST_HOE = register(new AmethystHoeItem());
	public static final Item AMETHYST_ARMOR_HELMET = register(new AmethystArmorItem.Helmet());
	public static final Item AMETHYST_ARMOR_CHESTPLATE = register(new AmethystArmorItem.Chestplate());
	public static final Item AMETHYST_ARMOR_LEGGINGS = register(new AmethystArmorItem.Leggings());
	public static final Item AMETHYST_ARMOR_BOOTS = register(new AmethystArmorItem.Boots());
	public static final Item CHROMIUM_ORE = register(SlothcraftModBlocks.CHROMIUM_ORE, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item CHROMIUM_ORE_BLOCK = register(SlothcraftModBlocks.CHROMIUM_ORE_BLOCK,
			SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item CHROMIUM_INGOT = register(new ChromiumIngotItem());
	public static final Item CHROMIUM_PICKAXE = register(new ChromiumPickaxeItem());
	public static final Item CHROMIUM_AXE = register(new ChromiumAxeItem());
	public static final Item CHROMIUM_SWORD = register(new ChromiumSwordItem());
	public static final Item CHROMIUM_SHOVEL = register(new ChromiumShovelItem());
	public static final Item CHROMIUM_HOE = register(new ChromiumHoeItem());
	public static final Item CHROMIUM_ARMOR_HELMET = register(new ChromiumArmorItem.Helmet());
	public static final Item CHROMIUM_ARMOR_CHESTPLATE = register(new ChromiumArmorItem.Chestplate());
	public static final Item CHROMIUM_ARMOR_LEGGINGS = register(new ChromiumArmorItem.Leggings());
	public static final Item CHROMIUM_ARMOR_BOOTS = register(new ChromiumArmorItem.Boots());
	public static final Item COPPER_PICKAXE = register(new CopperPickaxeItem());
	public static final Item COPPER_AXE = register(new CopperAxeItem());
	public static final Item COPPER_SWORD = register(new CopperSwordItem());
	public static final Item COPPER_SHOVEL = register(new CopperShovelItem());
	public static final Item COPPER_HOE = register(new CopperHoeItem());
	public static final Item COPPER_ARMOR_HELMET = register(new CopperArmorItem.Helmet());
	public static final Item COPPER_ARMOR_CHESTPLATE = register(new CopperArmorItem.Chestplate());
	public static final Item COPPER_ARMOR_LEGGINGS = register(new CopperArmorItem.Leggings());
	public static final Item COPPER_ARMOR_BOOTS = register(new CopperArmorItem.Boots());
	public static final Item IRIDIUM_ORE = register(SlothcraftModBlocks.IRIDIUM_ORE, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item IRIDIUM_ORE_BLOCK = register(SlothcraftModBlocks.IRIDIUM_ORE_BLOCK, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item IRIDIUM_INGOT = register(new IridiumIngotItem());
	public static final Item IRIDIUM_PICKAXE = register(new IridiumPickaxeItem());
	public static final Item IRIDIUM_AXE = register(new IridiumAxeItem());
	public static final Item IRIDIUM_SWORD = register(new IridiumSwordItem());
	public static final Item IRIDIUM_SHOVEL = register(new IridiumShovelItem());
	public static final Item IRIDIUM_HOE = register(new IridiumHoeItem());
	public static final Item IRIDIUM_ARMOR_HELMET = register(new IridiumArmorItem.Helmet());
	public static final Item IRIDIUM_ARMOR_CHESTPLATE = register(new IridiumArmorItem.Chestplate());
	public static final Item IRIDIUM_ARMOR_LEGGINGS = register(new IridiumArmorItem.Leggings());
	public static final Item IRIDIUM_ARMOR_BOOTS = register(new IridiumArmorItem.Boots());
	public static final Item JADE_ORE = register(SlothcraftModBlocks.JADE_ORE, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item JADE_ORE_BLOCK = register(SlothcraftModBlocks.JADE_ORE_BLOCK, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item JADE_GEM = register(new JadeGemItem());
	public static final Item JADE_PICKAXE = register(new JadePickaxeItem());
	public static final Item JADE_AXE = register(new JadeAxeItem());
	public static final Item JADE_SWORD = register(new JadeSwordItem());
	public static final Item JADE_SHOVEL = register(new JadeShovelItem());
	public static final Item JADE_HOE = register(new JadeHoeItem());
	public static final Item JADE_ARMOR_HELMET = register(new JadeArmorItem.Helmet());
	public static final Item JADE_ARMOR_CHESTPLATE = register(new JadeArmorItem.Chestplate());
	public static final Item JADE_ARMOR_LEGGINGS = register(new JadeArmorItem.Leggings());
	public static final Item JADE_ARMOR_BOOTS = register(new JadeArmorItem.Boots());
	public static final Item LEAD_ORE = register(SlothcraftModBlocks.LEAD_ORE, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item LEAD_ORE_BLOCK = register(SlothcraftModBlocks.LEAD_ORE_BLOCK, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item LEAD_INGOT = register(new LeadIngotItem());
	public static final Item LEAD_PICKAXE = register(new LeadPickaxeItem());
	public static final Item LEAD_AXE = register(new LeadAxeItem());
	public static final Item LEAD_SWORD = register(new LeadSwordItem());
	public static final Item LEAD_SHOVEL = register(new LeadShovelItem());
	public static final Item LEAD_HOE = register(new LeadHoeItem());
	public static final Item LEAD_ARMOR_HELMET = register(new LeadArmorItem.Helmet());
	public static final Item LEAD_ARMOR_CHESTPLATE = register(new LeadArmorItem.Chestplate());
	public static final Item LEAD_ARMOR_LEGGINGS = register(new LeadArmorItem.Leggings());
	public static final Item LEAD_ARMOR_BOOTS = register(new LeadArmorItem.Boots());
	public static final Item MITHRIL_ORE = register(SlothcraftModBlocks.MITHRIL_ORE, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item MITHRIL_ORE_BLOCK = register(SlothcraftModBlocks.MITHRIL_ORE_BLOCK, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item MITHRIL_INGOT = register(new MithrilIngotItem());
	public static final Item MITHRIL_PICKAXE = register(new MithrilPickaxeItem());
	public static final Item MITHRIL_AXE = register(new MithrilAxeItem());
	public static final Item MITHRIL_SWORD = register(new MithrilSwordItem());
	public static final Item MITHRIL_SHOVEL = register(new MithrilShovelItem());
	public static final Item MITHRIL_HOE = register(new MithrilHoeItem());
	public static final Item MITHRIL_ARMOR_HELMET = register(new MithrilArmorItem.Helmet());
	public static final Item MITHRIL_ARMOR_CHESTPLATE = register(new MithrilArmorItem.Chestplate());
	public static final Item MITHRIL_ARMOR_LEGGINGS = register(new MithrilArmorItem.Leggings());
	public static final Item MITHRIL_ARMOR_BOOTS = register(new MithrilArmorItem.Boots());
	public static final Item NICKEL_ORE = register(SlothcraftModBlocks.NICKEL_ORE, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item NICKEL_ORE_BLOCK = register(SlothcraftModBlocks.NICKEL_ORE_BLOCK, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item NICKEL_INGOT = register(new NickelIngotItem());
	public static final Item NICKEL_PICKAXE = register(new NickelPickaxeItem());
	public static final Item NICKEL_AXE = register(new NickelAxeItem());
	public static final Item NICKEL_SWORD = register(new NickelSwordItem());
	public static final Item NICKEL_SHOVEL = register(new NickelShovelItem());
	public static final Item NICKEL_HOE = register(new NickelHoeItem());
	public static final Item NICKEL_ARMOR_HELMET = register(new NickelArmorItem.Helmet());
	public static final Item NICKEL_ARMOR_CHESTPLATE = register(new NickelArmorItem.Chestplate());
	public static final Item NICKEL_ARMOR_LEGGINGS = register(new NickelArmorItem.Leggings());
	public static final Item NICKEL_ARMOR_BOOTS = register(new NickelArmorItem.Boots());
	public static final Item OSMIUM_ORE = register(SlothcraftModBlocks.OSMIUM_ORE, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item OSMIUM_ORE_BLOCK = register(SlothcraftModBlocks.OSMIUM_ORE_BLOCK, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item OSMIUM_INGOT = register(new OsmiumIngotItem());
	public static final Item OSMIUM_PICKAXE = register(new OsmiumPickaxeItem());
	public static final Item OSMIUM_AXE = register(new OsmiumAxeItem());
	public static final Item OSMIUM_SWORD = register(new OsmiumSwordItem());
	public static final Item OSMIUM_SHOVEL = register(new OsmiumShovelItem());
	public static final Item OSMIUM_HOE = register(new OsmiumHoeItem());
	public static final Item OSMIUM_ARMOR_HELMET = register(new OsmiumArmorItem.Helmet());
	public static final Item OSMIUM_ARMOR_CHESTPLATE = register(new OsmiumArmorItem.Chestplate());
	public static final Item OSMIUM_ARMOR_LEGGINGS = register(new OsmiumArmorItem.Leggings());
	public static final Item OSMIUM_ARMOR_BOOTS = register(new OsmiumArmorItem.Boots());
	public static final Item PLATINUM_ORE = register(SlothcraftModBlocks.PLATINUM_ORE, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item PLATINUM_ORE_BLOCK = register(SlothcraftModBlocks.PLATINUM_ORE_BLOCK,
			SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item PLATINUM_INGOT = register(new PlatinumIngotItem());
	public static final Item PLATINUM_PICKAXE = register(new PlatinumPickaxeItem());
	public static final Item PLATINUM_AXE = register(new PlatinumAxeItem());
	public static final Item PLATINUM_SWORD = register(new PlatinumSwordItem());
	public static final Item PLATINUM_SHOVEL = register(new PlatinumShovelItem());
	public static final Item PLATINUM_HOE = register(new PlatinumHoeItem());
	public static final Item PLATINUM_ARMOR_HELMET = register(new PlatinumArmorItem.Helmet());
	public static final Item PLATINUM_ARMOR_CHESTPLATE = register(new PlatinumArmorItem.Chestplate());
	public static final Item PLATINUM_ARMOR_LEGGINGS = register(new PlatinumArmorItem.Leggings());
	public static final Item PLATINUM_ARMOR_BOOTS = register(new PlatinumArmorItem.Boots());
	public static final Item RUBY_ORE = register(SlothcraftModBlocks.RUBY_ORE, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item RUBY_ORE_BLOCK = register(SlothcraftModBlocks.RUBY_ORE_BLOCK, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item RUBY_GEM = register(new RubyGemItem());
	public static final Item RUBY_PICKAXE = register(new RubyPickaxeItem());
	public static final Item RUBY_AXE = register(new RubyAxeItem());
	public static final Item RUBY_SWORD = register(new RubySwordItem());
	public static final Item RUBY_SHOVEL = register(new RubyShovelItem());
	public static final Item RUBY_HOE = register(new RubyHoeItem());
	public static final Item RUBY_ARMOR_HELMET = register(new RubyArmorItem.Helmet());
	public static final Item RUBY_ARMOR_CHESTPLATE = register(new RubyArmorItem.Chestplate());
	public static final Item RUBY_ARMOR_LEGGINGS = register(new RubyArmorItem.Leggings());
	public static final Item RUBY_ARMOR_BOOTS = register(new RubyArmorItem.Boots());
	public static final Item SILVER_ORE = register(SlothcraftModBlocks.SILVER_ORE, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item SILVER_ORE_BLOCK = register(SlothcraftModBlocks.SILVER_ORE_BLOCK, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item SILVER_INGOT = register(new SilverIngotItem());
	public static final Item SILVER_PICKAXE = register(new SilverPickaxeItem());
	public static final Item SILVER_AXE = register(new SilverAxeItem());
	public static final Item SILVER_SWORD = register(new SilverSwordItem());
	public static final Item SILVER_SHOVEL = register(new SilverShovelItem());
	public static final Item SILVER_HOE = register(new SilverHoeItem());
	public static final Item SILVER_ARMOR_HELMET = register(new SilverArmorItem.Helmet());
	public static final Item SILVER_ARMOR_CHESTPLATE = register(new SilverArmorItem.Chestplate());
	public static final Item SILVER_ARMOR_LEGGINGS = register(new SilverArmorItem.Leggings());
	public static final Item SILVER_ARMOR_BOOTS = register(new SilverArmorItem.Boots());
	public static final Item STEEL_ORE_BLOCK = register(SlothcraftModBlocks.STEEL_ORE_BLOCK, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item STEEL_INGOT = register(new SteelIngotItem());
	public static final Item STEEL_PICKAXE = register(new SteelPickaxeItem());
	public static final Item STEEL_AXE = register(new SteelAxeItem());
	public static final Item STEEL_SWORD = register(new SteelSwordItem());
	public static final Item STEEL_SHOVEL = register(new SteelShovelItem());
	public static final Item STEEL_HOE = register(new SteelHoeItem());
	public static final Item STEEL_ARMOR_HELMET = register(new SteelArmorItem.Helmet());
	public static final Item STEEL_ARMOR_CHESTPLATE = register(new SteelArmorItem.Chestplate());
	public static final Item STEEL_ARMOR_LEGGINGS = register(new SteelArmorItem.Leggings());
	public static final Item STEEL_ARMOR_BOOTS = register(new SteelArmorItem.Boots());
	public static final Item TIN_ORE = register(SlothcraftModBlocks.TIN_ORE, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item TIN_ORE_BLOCK = register(SlothcraftModBlocks.TIN_ORE_BLOCK, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item TIN_INGOT = register(new TinIngotItem());
	public static final Item TIN_PICKAXE = register(new TinPickaxeItem());
	public static final Item TIN_AXE = register(new TinAxeItem());
	public static final Item TIN_SWORD = register(new TinSwordItem());
	public static final Item TIN_SHOVEL = register(new TinShovelItem());
	public static final Item TIN_HOE = register(new TinHoeItem());
	public static final Item TIN_ARMOR_HELMET = register(new TinArmorItem.Helmet());
	public static final Item TIN_ARMOR_CHESTPLATE = register(new TinArmorItem.Chestplate());
	public static final Item TIN_ARMOR_LEGGINGS = register(new TinArmorItem.Leggings());
	public static final Item TIN_ARMOR_BOOTS = register(new TinArmorItem.Boots());
	public static final Item TITANIUM_ORE = register(SlothcraftModBlocks.TITANIUM_ORE, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item TITANIUM_ORE_BLOCK = register(SlothcraftModBlocks.TITANIUM_ORE_BLOCK,
			SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item TITANIUM_INGOT = register(new TitaniumIngotItem());
	public static final Item TITANIUM_PICKAXE = register(new TitaniumPickaxeItem());
	public static final Item TITANIUM_AXE = register(new TitaniumAxeItem());
	public static final Item TITANIUM_SWORD = register(new TitaniumSwordItem());
	public static final Item TITANIUM_SHOVEL = register(new TitaniumShovelItem());
	public static final Item TITANIUM_HOE = register(new TitaniumHoeItem());
	public static final Item TITANIUM_ARMOR_HELMET = register(new TitaniumArmorItem.Helmet());
	public static final Item TITANIUM_ARMOR_CHESTPLATE = register(new TitaniumArmorItem.Chestplate());
	public static final Item TITANIUM_ARMOR_LEGGINGS = register(new TitaniumArmorItem.Leggings());
	public static final Item TITANIUM_ARMOR_BOOTS = register(new TitaniumArmorItem.Boots());
	public static final Item URANIUM_ORE = register(SlothcraftModBlocks.URANIUM_ORE, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item URANIUM_ORE_BLOCK = register(SlothcraftModBlocks.URANIUM_ORE_BLOCK, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item URANIUM_INGOT = register(new UraniumIngotItem());
	public static final Item URANIUM_PICKAXE = register(new UraniumPickaxeItem());
	public static final Item URANIUM_AXE = register(new UraniumAxeItem());
	public static final Item URANIUM_SWORD = register(new UraniumSwordItem());
	public static final Item URANIUM_SHOVEL = register(new UraniumShovelItem());
	public static final Item URANIUM_HOE = register(new UraniumHoeItem());
	public static final Item URANIUM_ARMOR_HELMET = register(new UraniumArmorItem.Helmet());
	public static final Item URANIUM_ARMOR_CHESTPLATE = register(new UraniumArmorItem.Chestplate());
	public static final Item URANIUM_ARMOR_LEGGINGS = register(new UraniumArmorItem.Leggings());
	public static final Item URANIUM_ARMOR_BOOTS = register(new UraniumArmorItem.Boots());
	public static final Item ZINC_ORE = register(SlothcraftModBlocks.ZINC_ORE, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item ZINC_ORE_BLOCK = register(SlothcraftModBlocks.ZINC_ORE_BLOCK, SlothcraftModTabs.TAB_SLOTH_CRAFT_ORES_CREATIVE_TAB);
	public static final Item ZINC_INGOT = register(new ZincIngotItem());
	public static final Item ZINC_PICKAXE = register(new ZincPickaxeItem());
	public static final Item ZINC_AXE = register(new ZincAxeItem());
	public static final Item ZINC_SWORD = register(new ZincSwordItem());
	public static final Item ZINC_SHOVEL = register(new ZincShovelItem());
	public static final Item ZINC_HOE = register(new ZincHoeItem());
	public static final Item ZINC_ARMOR_HELMET = register(new ZincArmorItem.Helmet());
	public static final Item ZINC_ARMOR_CHESTPLATE = register(new ZincArmorItem.Chestplate());
	public static final Item ZINC_ARMOR_LEGGINGS = register(new ZincArmorItem.Leggings());
	public static final Item ZINC_ARMOR_BOOTS = register(new ZincArmorItem.Boots());

	private static Item register(Item item) {
		REGISTRY.add(item);
		return item;
	}

	private static Item register(Block block, CreativeModeTab tab) {
		return register(new BlockItem(block, new Item.Properties().tab(tab)).setRegistryName(block.getRegistryName()));
	}

	@SubscribeEvent
	public static void registerItems(RegistryEvent.Register<Item> event) {
		event.getRegistry().registerAll(REGISTRY.toArray(new Item[0]));
	}
}
